import type { Collection } from "./types";

export const collections: Collection[] = [
  {
    slug: "best-for-hackathons",
    title: "Best APIs for Hackathons",
    subtitle: "Ship in 48 hours",
    description: "APIs with the easiest setup, highest free limits, and best documentation — picked for shipping speed. All no credit card required.",
    icon: "Zap",
    providerSlugs: ["groq", "gemini", "openrouter", "deepseek", "deepgram", "huggingface", "fal", "elevenlabs", "jina", "together"],
    isPublished: true,
  },
  {
    slug: "openai-alternatives",
    title: "OpenAI Alternatives",
    subtitle: "GPT-4 quality, free",
    description: "Providers offering comparable or better models than OpenAI, all with real free tiers and OpenAI-compatible APIs.",
    icon: "RefreshCw",
    providerSlugs: ["groq", "gemini", "openrouter", "deepseek", "mistral", "cerebras", "fireworks", "together", "sambanova", "cohere"],
    isPublished: true,
  },
  {
    slug: "no-credit-card",
    title: "No Credit Card Required",
    subtitle: "Email-only signup",
    description: "Every API in this list can be signed up for with just an email address. No payment details needed, ever.",
    icon: "CreditCard",
    providerSlugs: [
      "groq", "gemini", "openrouter", "deepseek", "cerebras", "sambanova",
      "huggingface", "mistral", "deepgram", "jina", "voyage", "nomic", "mixedbread",
      "elevenlabs", "neets", "gladia", "playht", "assemblyai",
      "fal", "replicate", "leonardo", "stability",
      "runwayml", "lumaai", "tavily", "perplexity",
      "fireworks", "together", "modal", "lemonfox", "cohere",
      "hyperbolic", "glhf", "lambda", "lepton", "novita",
      "nvidia-nim", "ai21", "cloudflare-workers-ai", "upstage", "writer", "grok",
    ],
    isPublished: true,
  },
  {
    slug: "best-image-apis",
    title: "Best Image Generation APIs",
    subtitle: "Diffusion models ranked",
    description: "Top providers for generating images via FLUX, Stable Diffusion, and other diffusion models. From free to production-grade.",
    icon: "ImageIcon",
    providerSlugs: ["fal", "replicate", "stability", "leonardo", "hyperbolic", "novita", "nvidia-nim"],
    isPublished: true,
  },
  {
    slug: "speech-stack",
    title: "Build a Voice App",
    subtitle: "STT + TTS + realtime",
    description: "Everything you need to add voice to your application: speech-to-text, text-to-speech, and real-time audio streaming.",
    icon: "Mic",
    providerSlugs: ["deepgram", "elevenlabs", "assemblyai", "gladia", "playht", "neets", "google-tts"],
    isPublished: true,
  },
  {
    slug: "hidden-gems",
    title: "Hidden Gems",
    subtitle: "Underrated picks",
    description: "APIs that don't get enough attention. High quality, generous free tiers, smaller user base — worth knowing about.",
    icon: "Gem",
    providerSlugs: ["jina", "voyage", "nomic", "mixedbread", "cerebras", "hyperbolic", "glhf", "chutes", "cloudflare-workers-ai", "tavily", "neets"],
    isPublished: true,
  },
  {
    slug: "video-generation",
    title: "AI Video Generation APIs",
    subtitle: "Text-to-video & image-to-video",
    description: "The best APIs for generating video from text or images. From short clips to cinematic sequences.",
    icon: "Clapperboard",
    providerSlugs: ["runwayml", "lumaai", "fal", "replicate"],
    isPublished: true,
  },
  {
    slug: "chinese-ai-apis",
    title: "Chinese AI APIs",
    subtitle: "Top providers from China",
    description: "The best Chinese LLM providers with free tiers. Many offer generous token quotas and are optimized for Chinese-language tasks.",
    icon: "Globe",
    providerSlugs: [
      "deepseek", "siliconflow", "moonshot", "zhipu", "dashscope",
      "minimax", "baichuan", "hunyuan", "iflytek-spark", "volcengine",
      "infini-ai", "stepfun", "modelscope", "yi-01ai", "sensenova",
      "tiangong", "360gpt",
    ],
    isPublished: true,
  },
  {
    slug: "rag-stack",
    title: "Build a RAG Pipeline",
    subtitle: "Embeddings + reranking + search",
    description: "The best APIs for Retrieval-Augmented Generation: embeddings, reranking, web scraping, and semantic search.",
    icon: "Search",
    providerSlugs: ["jina", "voyage", "nomic", "mixedbread", "cohere", "tavily", "perplexity"],
    isPublished: true,
  },
  {
    slug: "agent-platforms",
    title: "AI Agent Platforms",
    subtitle: "Build agents, no infra",
    description: "Platforms for building and deploying AI agents without managing infrastructure. Many include free tiers with powerful underlying models.",
    icon: "Bot",
    providerSlugs: ["coze", "yuanqi", "coworker", "modal", "cloudflare-workers-ai", "lepton"],
    isPublished: true,
  },
];

export const getCollectionBySlug = (slug: string) => collections.find((c) => c.slug === slug);
